name: Test Compilazione # Action name
on:
  push:
    branches:
      - 'main'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Download file della Repo
        uses: actions/checkout@v4
      - name: Compilazione del file della Relazione
        uses: xu-cheng/latex-action@v3
        with: # insert here files to compile
          working_directory: Notebook
          root_file: Notebook.tex
      - name: Ridenominazione files
        run: mv Notebook/Notebook.pdf Notebook/Quadernino.pdf
      - name: Caricamento della Release temporanea
        uses: actions/upload-artifact@v3
        with: 
          name: Quadernino
          path: Notebook/Quadernino.pdf
